### ISSUE TITLE
'WelcomeWindow' does not contain a definition for 'Initialize' - Windows 10 Unity v2021.3.16f1

### ISSUE THREAD

**Issue by Briggs599** [DolbyIO/comms-sdk-unity#20]
Unity v2021.3.16f1, Windows 10 Enterprise

The Dolby.io Comms package was installing fine up until this week. When installing today I encountered these issues:

```
Library\PackageCache\dolbyio.comms.unity@f6178df296\Editor\WelcomeWindow.cs(36,35): error CS0117: 'WelcomeWindow' does not contain a definition for 'Initialize'

Failed to find entry-points:
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'DolbyI0.Comms.Unity.Editor, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
```
![unity-error](https://github.com/DolbyIO/comms-sdk-unity/assets/48164242/73ec71cd-d705-4764-8584-f506f5969bd1)

**Comment by 4thlabs** [comment]
Hi @Briggs599, would you mind specifying the version of the plugin you are using ?

**Comment by GaryMakinDolby** [comment]
I got the same error today, so it would have been v1.1.1.
