### ISSUE TITLE
Package Manager Fails to find "valid documentation" and "valid changelog" for the package.

### ISSUE THREAD

**Issue by Briggs599** [DolbyIO/comms-sdk-unity#21]
`[Package Manager Window] Unable to find valid documentation for this package.
UnityEngine.AsyncOperation:InvokeCompletionEvent ()`
![other-unity-error](https://github.com/DolbyIO/comms-sdk-unity/assets/48164242/6d205596-7c66-488a-bc9b-767e8cecf3bb)

**Comment by GaryMakinDolby** [comment]
In the manifest

- `documentationUrl` should link to https://api-references.dolby.io/comms-sdk-dotnet/documentation/unity/getting-started/installation.html

- `changelogUrl` should be filled out. If it is impossible to know the correct URL at build time, link to https://github.com/DolbyIO/comms-sdk-unity/releases
