### ISSUE TITLE
Dolby.io Manager logs error if no Credentials component added

### ISSUE THREAD

**Issue by GaryMakinDolby** [DolbyIO/comms-sdk-unity#45]
The Dolby IO Manager component logs an error message in the `Awake()` method if neither of the two possible Credential components have been added.

There are other ways of supplying the credentials (as the Shared Scene Sample demonstrates), so this should not be an error.

**Comment by 4thlabs** [comment]
It's actually right. The Shared Sample needs to be modified to show the good way of doing it.
